### ISSUE TITLE
xport.to_numpy() API naming suggestion

### ISSUE THREAD

**Issue by chesnokov-yuriy** [selik/xport#12]
Very convenient library for quick binary XPT files serialization with `xport.to_*` functions. However it would be naturally named after returned object instead of NumPy library name:

`xport.to_dict()`
`xport.to_ndarray()`
`xport.to_dataframe()`

**Comment by selik** [comment]
How would you handle the distinction between rows (list of tuples) and columns (dict of lists)?

**Comment by chesnokovyuriy** [comment]
no, I meant more suitable naming to existing api

`xport.to_rows()` -> `xport.to_list()`
`xport.to_columns()` -> `xport.to_dict()`
`xport.to_numpy()` -> `xport.to_ndarray()`
`xport.to_dataframe()` -> `xport.to_dataframe()`

based on returned data type, otherwise `to_dataframe()` would be named `to_pandas()` which is ambiguous if it is pandas DataFrame or DataSeries

**Comment by selik** [comment]
I agree that `to_numpy` could be better as `to_ndarray` but I'm not convinced that `to_list` is better than `to_rows`. Compare with Pandas' `iterrows`, `itertuples`, and `iteritems`. I always forget what the output of each is.

**Comment by selik** [comment]
I decided to switch to the standard `load` and `dump` pattern that many other file format libraries use: JSON, YAML, pickle, etc. I'll write documentation examples for how to convert to different structures.

**Comment by selik** [comment]
I'm deprecating the old `to_*` interface #34
