### ISSUE TITLE
Read CP-1252 character encoding

### ISSUE THREAD

**Issue by blumdrew** [selik/xport#30]
Is there any way to handle different character encoding sets? Most of the SAS files that I have to read are encoded in CP-1252 (gross, I know) and it looks there isn't a good way to handle that here

**Comment by selik** [comment]
@blumdrew I think that edit wouldn't be too bad in the code. I think the namestrs are ASCII while the observations could be other encodings. If you search through `xport.py` for `.decode` you'll find the places you can try modifying. For example, in `_parse_observation`:
https://github.com/selik/xport/blob/c705901f5e46bf3e5f9e32f27ed5a4e2916965af/xport.py#L390

I linked to the commit that's currently published on PyPI, rather than the latest commit in GitHub. I was in the middle of changing it here and left it in a broken state, I think.

**Comment by blumdrew** [comment]
Great, thanks for the tip. Ill see what I can do

**Comment by selik** [comment]
Looks like my distribution of Python doesn't have that encoding.
```
In [1]: 'Hello'.encode('CP-1252')
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-1-fed077a427be> in <module>
----> 1 'Hello'.encode('CP-1252')

LookupError: unknown encoding: CP-1252
```

**Comment by selik** [comment]
Since CP-1252 is almost the same as ISO-8859-1, one solution is to simply ignore/replace the errors.

**Comment by selik** [comment]
I'll add support for CP-1252 along with allowing any text encoding: #75
