### ISSUE TITLE
can't set variable.label as mentioned in example v.label = k.title(). It was working previously

### ISSUE THREAD

**Issue by sivakumar-python** [selik/xport#58]

**Comment by meain** [comment]
Pinning the pandas version to `1.0.3` seems to help.

**Comment by selik** [comment]
Pandas' `DataFrame._metadata` turned out to be not as well supported as it seemed from the documentation. I'll be switching to `DataFrame.attrs` to store XPORT-format dataset metadata. See [Pandas issue 44866](https://github.com/pandas-dev/pandas/issues/44866).

In the meantime, I got `xport` working for the latest version of Pandas. #78
